fix: make components ssr/ssg compatible
emdgroup/react-lib pull request #1
Opened 2022-04-04 15:19 UTC by renet

I wasn't able to thoroughly test this, but it should work. :)

2022-04-04 15:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/emdgroup/react-lib?pullRequest=1) <br/>All committers have signed the CLA.

2022-04-04 16:49 UTC, monken commented
one minor thing

2022-04-04 16:49 UTC, monken commented on packages/query/src/index.ts
> +    const [online, setOnline] = useState((typeof navigator !== 'undefined' && navigator.onLine) ?? true);
this will set `online` to false if `navigator` is undefined. That's not the intention. I think 

```
(typeof navigator === 'undefined' ? true : navigator.onLine) ?? true
```

solves that.

2022-04-04 17:11 UTC, monken requested changes

2022-04-04 17:11 UTC, monken commented on packages/auth/src/index.tsx
> +                domainHint,
should be `domain_hint: domainHint`

2022-04-05 08:20 UTC, renet commented on packages/query/src/index.ts
> +    const [online, setOnline] = useState((typeof navigator !== 'undefined' && navigator.onLine) ?? true);
```suggestion
    const [online, setOnline] = useState(typeof navigator !== 'undefined' ? (navigator.onLine ?? true) : true);
```
How about this?

2022-04-05 08:22 UTC, renet commented on packages/auth/src/index.tsx
> +                domainHint,
```suggestion
                domain_hint: domainHint,
```

2022-04-05 15:35 UTC, monken approved these changes

2022-04-05 15:36 UTC, merged