feat: add entrypoint param to login function
emdgroup/react-lib pull request #3
Opened 2022-04-05 15:34 UTC by renet

2022-04-05 15:46 UTC, monken requested changes

2022-04-05 15:46 UTC, monken commented on packages/auth/src/index.tsx
> +    login?: (entrypoint?: string) => void;
could you please make this an optional object instead? I anticipate that we will need additional parameters to log in in the future.

```
login?: (opts?: { entrypoint?: string }) => void;
```

2022-04-05 18:02 UTC, monken commented on packages/auth/src/index.tsx
> +    login?: (entrypoint?: string) => void;
so let's add the `{ redirect?: boolean }` here as well

2022-04-06 12:03 UTC, renet commented on packages/auth/src/index.tsx
> +    login?: (entrypoint?: string) => void;
Is it ok like I did it in the last commit?

2022-04-06 13:26 UTC, merged